### PR TITLE
Test and mark Python 3.12 support. Update setuptools support for >67

### PR DESCRIPTION
**Pull request by tonybaloney**
This package is broken in the latest version of setuptools, this PR fixes the issue and tests the patch on Python 3.12

### CODE REVIEW

**Comment by jmyersmsft** [comment]
@nechvatalp Can you review this? Looks like there are very few others who have permission.

**Comment by zooba** [comment]
@nechvatalp Any chance of a review?

**Comment by cmollgaard** [comment]
A review would be very helpful.
The PR seems to fix the problems with namespace in our 3.9 and 3.10 environments

**Comment by jmyersmsft** [comment]
Pinging some other folks who might be able to help: @crazy4pi314 @vtbassmatt @tedchamb

**Comment by vtbassmatt** [comment]
I haven't worked on this product in years, and wouldn't be comfortable approving a PR.

**Review by crazy4pi314 — COMMENTED** [review]
Looks good to me! Easy 3.12 upgrade party 🥳

**Comment by nechvatalp** [comment]
Looks good to me, thanks for your contribution

**Pull request merged**
